# Generated by Django 6.0.6 on 2026-06-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('star_count', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('facebook_link', models.URLField(blank=True, max_length=500)),
                ('instagram_link', models.URLField(blank=True, max_length=500)),
                ('twitter_link', models.URLField(blank=True, max_length=500)),
                ('whatsapp_link', models.URLField(blank=True, max_length=500)),
                ('tiktok_link', models.URLField(blank=True, max_length=500)),
                ('linkedin_link', models.URLField(blank=True, max_length=500)),
                ('youtube_link', models.URLField(blank=True, max_length=500)),
                ('primary_category_name', models.CharField(blank=True, max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
