# Generated by Django 6.0.6 on 2026-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
