# Generated by Django 6.0.6 on 2026-06-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_contact_date_lead_followup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversion_rating',
            field=models.CharField(choices=[('not_contacted', 'Not contacted'), ('A', 'A - Highly likely to convert'), ('B', 'B - Some interest'), ('C', 'C - Low interest'), ('D', 'D - Not interested / dead lead')], default='not_contacted', max_length=20),
        ),
    ]
