# Generated by Django 6.0.6 on 2026-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_friday_hours_lead_monday_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='in_mall',
            field=models.BooleanField(default=False),
        ),
    ]
